import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from "../components/Skills"
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] h-screen text-white overflow-scroll overflow-x-hidden snap-y snap-mandatory ease-in duration-300 lg:scrollbar scrollbar-thumb-[#F7AB0A] scrollbar-track-[#292929]" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />
      {/* hero */}
      <section id='hero' className='snap-start z-30'>
        <Hero />
      </section>
      {/* about */}
      <section id='about' className='h-screen snap-center '>
        <About />
      </section>
      {/* experience */}
      <section className='h-screen snap-start' id='experience'>
        <Experience />
      </section>
      {/* skils */}
      <section className='h-screen snap-start' id='skills'>
        <Skills />
      </section>
      <section className='h-screen snap-start' id='projects'>
        <Projects />
      </section>
      {/* contact section */}
      <section className='h-screen snap-start' id='contact'>
        <Contact />
      </section>

      <Link href="#hero" className=''>
        <footer className='sticky bottom-5 w-full  justify-center flex'>
          <div className=''>
            <img className='h-12 w-12 rounded-full cursor-pointer hover:grayscale filter' src="https://avatars.githubusercontent.com/u/70938131?v=4" alt="" />
          </div>
        </footer>
      </Link>


    </div>
  )
}

export default Home
